### ISSUE TITLE
Blunderbust crash

### ISSUE THREAD

**Issue by Hamsterrhino** [TheBigNickel/historicalGuns#1]
Right after projectile hits something game hard crashes
`[22:03:36] [1/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: Read underflow 0 of 11 bytes caused by WingSlot in HandlePacket
   at Terraria.ModLoader.ModNet.HandleModPacket(BinaryReader reader, Int32 whoAmI, Int32 length)
   at DMD<Terraria.MessageBuffer::GetData>(MessageBuffer this, Int32 start, Int32 length, Int32& messageType)
   at MagicStorageExtra.Edits.Detours.Vanilla.MessageBuffer_GetData(orig_GetData orig, MessageBuffer self, Int32 start, Int32 length, Int32& messageType) in MagicStorageExtra\Edits\Detours\Vanilla.NetMessage.cs:line 159
   at Hook<Terraria.MessageBuffer::GetData>?37766504(MessageBuffer , Int32 , Int32 , Int32& )
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   at Terraria.Netplay.OnUpdate()
   at DMD<Terraria.Main::DoUpdate>(Main this, GameTime gameTime)
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

[22:03:38] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at pinkymod.Global.PmodGlobalItem.tryAutoload(Item item, Int32 searchX, Int32 searchY)
   at pinkymod.Global.PmodGlobalItem.PostUpdate(Item item)
   at Terraria.ModLoader.ItemLoader.PostUpdate(Item item)
   at DMD<Terraria.Item::UpdateItem>(Item this, Int32 i)
   at DMD<Terraria.Main::DoUpdate>(Main this, GameTime gameTime)
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

[22:03:38] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at pinkymod.Global.PmodGlobalItem.PostUpdate(Item item)
   at Terraria.ModLoader.ItemLoader.PostUpdate(Item item)
   at DMD<Terraria.Item::UpdateItem>(Item this, Int32 i)
   at DMD<Terraria.Main::DoUpdate>(Main this, GameTime gameTime)
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)

[22:03:40] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at pinkymod.PmodPlayer.PostUpdate()
   at Terraria.ModLoader.PlayerHooks.PostUpdate(Player player)
   at DMD<Terraria.Player::Update>(Player this, Int32 i)
   at DMD<Terraria.Main::DoUpdate>(Main this, GameTime gameTime)
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)`

**Comment by Hamsterrhino** [comment]
Found also El Habanero having same problem, I assume because of particle used for shooting
